# `conda env create -f environment.yml` (initial create); `conda env update --name cs50 -f environment.yml` (if updated)
name: cs50
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - bokeh
  - conda-forge::gh
  - ipykernel
  - matplotlib 
  - numpy
  - pandas
  - pillow
  - pip
  - PuLP
  - pyarrow
  - scikit-learn
  - scipy
  - seaborn